config: 
  plugins: 
    metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases: 
    - duration: 20
      arrivalRate: 10
scenarios: 
  - name: 'Sessions Flow (register + login)'
    flow: 
      - log: 'Creamos un usuario de prueba'
      - get:
          url: /mocking/user
          capture: 
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.gender"
              as: "gender"
            - json: "$.password"
              as: "password"
      - log: 'Registramos el usuario' 
      - post:
          url: /api/sessions/register          
          json:
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            gender: "{{gender}}"
            password: "{{password}}"
      - think: 2
      - log: 'login user'
      - post:
          url: /api/sessions/login
          json:
            username: "{{email}}"
            password: "{{password}}"